[package]
name = "rusty-ant"
version = "1.0.0"
authors = ["Kurnevsky Evgeny <kurnevsky@gmail.com>"]
license = "GPL-3.0"

[dependencies]
time = "0.1.16"

[profile.dev]
opt-level = 0
lto = false
debug = true

[profile.release]
opt-level = 3
lto = true
debug = false
