condense_wildcard_suffixes = true
imports_layout = "HorizontalVertical"
merge_imports = true
max_width = 120
normalize_comments = true
reorder_impl_items = true
spaces_around_ranges = true
tab_spaces = 2
use_try_shorthand = true
wrap_comments = true
match_arm_blocks = false
unstable_features = true
